# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

swagger: '2.0'
info:
  version: 0.0.1
  title: Shanoir NG Studies Microservice - Acquisition equipments managment
  description: Microservice API for Shanoir NG acquisition equipments managment
produces:
  - application/json
paths:
  /acquisitionequipments:
    get:
      operationId: findAcquisitionEquipments
      description: Returns all the acquisition equipments
      responses:
        '200':
          description: found acquisition equipments
          schema:
            type: array
            items:
              $ref: '#/definitions/AcquisitionEquipmentDTO'
        '204':
          description: no acquisition equipment found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      operationId: saveNewAcquisitionEquipment
      description: Saves a new acquisition equipment
      consumes:
        - application/json
      parameters:
        - name: acquisitionEquipment
          in: body
          description: acquisition equipment to create
          required: true
          schema:
            $ref: '#/definitions/AcquisitionEquipment'
      responses:
        '200':
          description: created acquisition equipment
          schema:
            $ref: '#/definitions/AcquisitionEquipmentDTO'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/acquisitionequipments/{acquisitionEquipmentId}':
    get:
      operationId: findAcquisitionEquipmentById
      description: >-
        If exists, returns the acquisition equipment corresponding to the given
        id
      parameters:
        - $ref: '#/parameters/acquisitionEquipmentId'
      responses:
        '200':
          description: found acquisition equipment
          schema:
            $ref: '#/definitions/AcquisitionEquipmentDTO'
        '204':
          description: no acquisition equipment found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    put:
      operationId: updateAcquisitionEquipment
      description: Updates a acquisition equipment
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/acquisitionEquipmentId'
        - name: acquisitionequipment
          in: body
          description: acquisition equipment to update
          required: true
          schema:
            $ref: '#/definitions/AcquisitionEquipment'
      responses:
        '200':
          description: acquisition equipment updated
        '204':
          description: acquisition equipment not found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    delete:
      operationId: deleteAcquisitionEquipment
      description: Deletes an acquisition equipment
      parameters:
        - $ref: '#/parameters/acquisitionEquipmentId'
      responses:
        '200':
          description: acquisition equipment deleted
        '204':
          description: no acquisition equipment found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
parameters:
  acquisitionEquipmentId:
    name: acquisitionEquipmentId
    in: path
    description: id of the acquisition equipment
    required: true
    type: integer
    format: int64
definitions:
  AcquisitionEquipment:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      center:
        $ref: '#/definitions/Center'
      manufacturerModel:
        $ref: '#/definitions/ManufacturerModel'
      serialNumber:
        type: string
  AcquisitionEquipmentDTO:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      center:
        $ref: '#/definitions/CenterDTO'
      manufacturerModel:
        $ref: '#/definitions/ManufacturerModel'
      serialNumber:
        type: string
  Center:
    type: object
  CenterDTO:
    type: object
  DatasetModalityType:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Manufacturer:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  ManufacturerModel:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      datasetModalityType:
        $ref: '#/definitions/DatasetModalityType'
      manufacturer:
        $ref: '#/definitions/Manufacturer'
      name:
        type: string
  ErrorModel:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: object
      message:
        type: string
