# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

openapi: "3.0.0"
info:
  version: 0.0.1
  title: Shanoir NG Studies Microservice
  description: Microservice API for Shanoir NG study managment
produces:
  - application/json
paths:
  /studies:
    get:
      operationId: findStudies
      description: 'If exists, returns the studies that the user is allowed to see'
      responses:
        '200':
          description: found studies
          schema:
            type: array
            items:
              $ref: '#/definitions/Study'
        '204':
          description: no study found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      operationId: saveNewStudy
      description: Saves a new study
      consumes:
        - application/json
      parameters:
        - name: study
          in: body
          description: study to create
          required: true
          schema:
            $ref: '#/definitions/Study'
      responses:
        '200':
          description: created study
          schema:
            $ref: '#/definitions/Study'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/studies/{studyId}':
    get:
      operationId: findStudyById
      description: 'If exists, returns the study corresponding to the given id'
      parameters:
        - $ref: '#/parameters/studyId'
        - in: query
          name: withdata
          type: boolean
          description: Get study with all data or not.
      responses:
        '200':
          description: found study
          schema:
            $ref: '#/definitions/Study'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    put:
      operationId: updateStudy
      description: Updates a study
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/studyId'
        - name: study
          in: body
          description: study to update
          required: true
          schema:
            $ref: '#/definitions/Study'
      responses:
        '204':
          description: study updated
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    delete:
      operationId: deleteStudy
      description: Deletes a study
      parameters:
        - $ref: '#/parameters/studyId'
      responses:
        '204':
          description: study deleted
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/studies/{studyId}/members':
    put:
      operationId: addMemberToStudy
      description: Adds a member to a study
      parameters:
        - $ref: '#/parameters/studyId'
        - name: studyUser
          in: body
          description: relation between the study and an user
          required: true
          schema:
            $ref: '#/definitions/StudyUser'
      responses:
        '204':
          description: member added
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/studies/{studyId}/members/{memberId}':
    delete:
      operationId: removeMember
      description: Removes a member from a study
      parameters:
        - $ref: '#/parameters/studyId'
        - $ref: '#/parameters/memberId'
      responses:
        '204':
          description: member removed
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /studies/listwithcards:
    get:
      operationId: findStudiesWithStudyCardsByUserId
      description: >-
        If exists, returns the studies with theirs study cards that the user is
        allowed to see
      responses:
        '200':
          description: found studies
          schema:
            $ref: '#/definitions/SimpleStudyDTO'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /studies/names:
    get:
      operationId: findStudiesNames
      description: Returns id and name for all the studies
      responses:
        '200':
          description: found studies
          schema:
            type: array
            items:
              $ref: '#/definitions/IdNameDTO'
        '204':
          description: no study found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
parameters:
  studyId:
    name: studyId
    in: path
    description: id of the study
    required: true
    type: integer
    format: int64
  memberId:
    name: memberId
    in: path
    description: id of the member
    required: true
    type: integer
    format: int64
definitions:
  Center:
    type: object
  ExperimentalGroupOfSubjects:
    type: object
  IdNameDTO:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Study:
    type: object
    required:
      - id
      - name
      - status
    properties:
      clinical:
        type: boolean
      downloadableByDefault:
        type: boolean
      endDate:
        type: string
        format: date
      examinationIds:
        type: array
        items:
          type: integer
          format: int64
      experimentalGroupsOfSubjects:
        type: array
        items:
          $ref: '#/definitions/ExperimentalGroupOfSubjects'
      id:
        type: integer
        format: int64
      monoCenter:
        type: boolean
      name:
        type: string
      protocolFilePaths:
        type: array
        items:
          type: string
      status:
        $ref: '#/definitions/Status'
      startDate:
        type: string
        format: date
      studyCenterList:
        type: array
        items:
          $ref: '#/definitions/StudyCenter'
      studyStatus:
        type: integer
      studyType:
        type: integer
      studyUserList:
        type: array
        items:
          $ref: '#/definitions/StudyUser'
      subjectStudyList:
        type: array
        items:
          $ref: '#/definitions/SubjectStudy'
      timepoints:
        type: array
        items:
          $ref: '#/definitions/Timepoint'
      visibleByDefault:
        type: boolean
      withExamination:
        type: boolean
  SimpleStudyDTO:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      studyCards:
        type: array
        items:
          $ref: '#/definitions/SimpleStudyCardDTO'
  SimpleStudyCardDTO:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Status:
    type: object
    required:
      - id
      - labelName
    properties:
      id:
        type: integer
        format: int64
      labelName:
        type: string
  StudyCenter:
    type: object
    properties:
      center:
        $ref: '#/definitions/Center'
      id:
        type: integer
        format: int64
      study:
        $ref: '#/definitions/Study'
  StudyUser:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      receiveAnonymizationReport:
        type: boolean
      receiveNewImportReport:
        type: boolean
      studyId:
        type: integer
        format: int64
      studyUserType:
        type: integer
      userId:
        type: integer
        format: int64
  Subject:
    type: object
  SubjectStudy:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      physicallyInvolved:
        type: boolean
      study:
        $ref: '#/definitions/Study'
      subject:
        $ref: '#/definitions/Subject'
      subjectStudyIdentifier:
        type: string
      subjectType:
        type: integer
  Timepoint:
    type: object
    required:
      - id
    properties:
      comment:
        type: string
      days:
        type: integer
        format: int64
      id:
        type: integer
        format: int64
      name:
        type: string
      rank:
        type: integer
        format: int64
      study:
        $ref: '#/definitions/Study'
  ErrorModel:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: object
      message:
        type: string
