# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

openapi: "3.0.0"
info:
  version: 0.0.1
  title: Shanoir NG Studies Microservice - Manufacturer models management
  description: Microservice API for Shanoir NG manufacturer models management
produces:
  - application/json
paths:
  /manufacturermodels:
    get:
      operationId: findManufacturerModels
      description: Returns all the manufacturer models
      responses:
        '200':
          description: found manufacturer models
          schema:
            type: array
            items:
              $ref: '#/definitions/ManufacturerModel'
        '204':
          description: no manufacturer model found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      operationId: saveNewManufacturerModel
      description: Saves a new manufacturer model
      consumes:
        - application/json
      parameters:
        - name: manufacturerModel
          in: body
          description: manufacturer model to create
          required: true
          schema:
            $ref: '#/definitions/ManufacturerModel'
      responses:
        '200':
          description: created manufacturer model
          schema:
            $ref: '#/definitions/ManufacturerModel'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/manufacturermodels/{manufacturerModelId}':
    get:
      operationId: findManufacturerModelById
      description: 'If exists, returns the manufacturer model corresponding to the given id'
      parameters:
        - $ref: '#/parameters/manufacturerModelId'
      responses:
        '200':
          description: found manufacturer model
          schema:
            $ref: '#/definitions/ManufacturerModel'
        '204':
          description: no manufacturer model found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    put:
      operationId: updateManufacturerModel
      description: Updates a manufacturer model
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/manufacturerModelId'
        - name: manufacturer model
          in: body
          description: manufacturer model to update
          required: true
          schema:
            $ref: '#/definitions/ManufacturerModel'
      responses:
        '204':
          description: manufacturer model updated
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: manufacturer model not found
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /manufacturers:
    get:
      operationId: findManufacturers
      description: Returns all the manufacturers
      responses:
        '200':
          description: found manufacturers
          schema:
            type: array
            items:
              $ref: '#/definitions/Manufacturer'
        '204':
          description: no manufacturer found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      operationId: saveNewManufacturer
      description: Saves a new manufacturer
      consumes:
        - application/json
      parameters:
        - name: manufacturer
          in: body
          description: manufacturer to create
          required: true
          schema:
            $ref: '#/definitions/Manufacturer'
      responses:
        '200':
          description: created manufacturer
          schema:
            $ref: '#/definitions/Manufacturer'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/manufacturers/{manufacturerId}':
    get:
      operationId: findManufacturerById
      description: 'If exists, returns the manufacturer corresponding to the given id'
      parameters:
        - $ref: '#/parameters/manufacturerId'
      responses:
        '200':
          description: found manufacturer
          schema:
            $ref: '#/definitions/Manufacturer'
        '204':
          description: no manufacturer found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    put:
      operationId: updateManufacturer
      description: Updates a manufacturer
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/manufacturerId'
        - name: manufacturer
          in: body
          description: manufacturer to update
          required: true
          schema:
            $ref: '#/definitions/Manufacturer'
      responses:
        '204':
          description: manufacturer updated
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: manufacturer not found
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
parameters:
  manufacturerModelId:
    name: manufacturerModelId
    in: path
    description: id of the manufacturer model
    required: true
    type: integer
    format: int64
  manufacturerId:
    name: manufacturerId
    in: path
    description: id of the manufacturer
    required: true
    type: integer
    format: int64
definitions:
  DatasetModalityType:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Manufacturer:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  ManufacturerModel:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      datasetModalityType:
        $ref: '#/definitions/DatasetModalityType'
      manufacturer:
        $ref: '#/definitions/Manufacturer'
      name:
        type: string
  ErrorModel:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: object
      message:
        type: string
