#!/bin/sh

die() {
	echo "error: $*" >&2
	exit 1
}

[ $# -eq 1 ] || die "usage: $0 PASSWORD
	PASSWORD is the password of the 'ng-users' user in the master realm of
	the keycloak server"

export KEYCLOAK_USER="ng-users"
export KEYCLOAK_PASSWORD="$1"

case "$PROFILE" in
	'')
		die "env var PROFILE is empty (should contain either prod, qualif or dev)"
		;;
	qualif)
		kc_args="--spring.profiles.active=qualif"
		;;
	*)
		kc_args=""
		;;
esac


# abort on error
set -e

configure-hosts


echo "Initialize MariaDB and populate it"
init-mysql < /dev/null

echo "Create supervisor log directory"
mkdir -p /vol/log/supervisor

echo "Start the mysql server"
run-mysql </dev/null &
pid=$!
wait-mysql --timeout=5

# name of the mysql table
tbl="`echo "$MS" | sed s/-/_/g`"
if [ "$PROFILE" = dev ] ; then
	echo "Populate database"
	mysql -u root "$tbl" < /opt/cfg/shanoirng_users.sql
else
	echo "Populate database - create tables"
	mysql -u root "$tbl" < /opt/cfg/shanoirng_users_tables.sql

	echo "Populate database - import users from shanoir old"
	/opt/cfg/usersMigration.py
fi

# save the credential in the container config (/vol/ro/)
default="/vol/ro/default/msapp.sh"
echo "Save keycloak credential of $KEYCLOAK_USER in $default"
mkdir -p "`dirname "$default"`"
cat >"$default" <<EOF
#
# credential for the keycloak server
#  -> used for managing users in then shanoir-ng realm
#
export KEYCLOAK_USER='$KEYCLOAK_USER'
export KEYCLOAK_PASSWORD='$KEYCLOAK_PASSWORD'
EOF
chmod 0600 "$default"

echo "Initialize Keycloak database"
override                       \
       -e SHANOIR_SERVER_URL   \
       -e SMTP_HOST            \
       -e SMTP_PORT            \
       -z                 /opt/shanoir-ng/shanoir-ng-keycloak.jar BOOT-INF/classes/application.yml
su shanoir -c "java -jar /opt/shanoir-ng/shanoir-ng-keycloak.jar $kc_args"

echo "Stop mysql process"
kill $pid
wait
