#!/bin/sh

set -e

# Enables signals getting passed from startup script to JVM
# ensuring clean shutdown when container is stopped.
export LAUNCH_JBOSS_IN_BACKGROUND=1

export JBOSS_HOME=/opt/keycloak

#if [ $KEYCLOAK_USER ] && [ $KEYCLOAK_PASSWORD ]; then
#    /opt/jboss/keycloak-demo/keycloak/bin/add-user-keycloak.sh -u $KEYCLOAK_USER -p $KEYCLOAK_PASSWORD >/dev/null
#fi

# select the adequate theme
echo "Applying profile '$PROFILE'"
(cd /opt/keycloak/themes/shanoir-theme/login/ && cp "theme-$PROFILE.properties" "theme.properties")

# runtime config
if [ -z "$DISABLE_RUNTIME_CONFIG" ]
then
	# - shanoir theme
	override -e SHANOIR_SERVER_URL -e DOCKER_PREFIX /opt/keycloak/themes/shanoir-theme/login/theme.properties
	# - shanoir-ng-keycloak-auth
	override -e SHANOIR_SERVER_URL -e DOCKER_PREFIX -z /opt/jboss/keycloak/providers/shanoir-ng-keycloak-auth.jar application.properties
	# - keycloak database
	keycloak-runtime-config
fi

# cache/log/tmp directories
for dir in /vol/cache/keycloak /vol/log/keycloak /tmp/keycloak
do
	mkdir -p "$dir"
	chown shanoir: "$dir"
done


wait-mysql


exec su - shanoir -c "/opt/keycloak/bin/standalone.sh  -b 0.0.0.0 -bmanagement 0.0.0.0
# TODO: remove ?
#	-Dkeycloak.import=/opt/jboss/keycloak-demo/keycloak/testrealm.json
"
