# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

services:
  #
  # Users microservice - native
  #
  users:
    container_name: "${SHANOIR_PREFIX}users"
    build: !reset null
    image: "shanoir-ng-users-native:latest"
    entrypoint: ["/workspace/org.shanoir.ng.ShanoirUsersApplication",
                 "-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts",
                 "-Djavax.net.ssl.trustStorePassword=changeit",
                 "-Djavax.net.ssl.trustStoreType=JKS"]
    environment:
      - SHANOIR_PREFIX
      - SHANOIR_URL_SCHEME
      - SHANOIR_URL_HOST
      - SHANOIR_KEYCLOAK_USER
      - SHANOIR_KEYCLOAK_PASSWORD
      - SHANOIR_ADMIN_EMAIL
      - SHANOIR_CERTIFICATE
      - SHANOIR_CERTIFICATE_PEM_CRT
      - SHANOIR_CERTIFICATE_PEM_KEY
      - SHANOIR_MIGRATION
      - VIP_SERVICE_EMAIL
      - SHANOIR_SMTP_HOST
      - SHANOIR_SMTP_PORT
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    volumes:
      - "logs:/var/log/shanoir-ng-logs"
      - "certificate-share-data:/etc/ssl/certs/java:ro"
    networks:
      - shanoir_ng_network
    ports:
      - "9901:9901"
      - "9911:9911"
    depends_on:
      init-cert-and-logs:
        condition: service_completed_successfully
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
  #
  # Studies microservice - native
  #
  studies:
    container_name: "${SHANOIR_PREFIX}studies"
    build: !reset null
    image: "shanoir-ng-studies-native:latest"
    entrypoint: ["/workspace/org.shanoir.ng.ShanoirStudiesApplication",
                 "-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts",
                 "-Djavax.net.ssl.trustStorePassword=changeit",
                 "-Djavax.net.ssl.trustStoreType=JKS"]
    environment:
      - SHANOIR_PREFIX
      - SHANOIR_URL_SCHEME
      - SHANOIR_URL_HOST
      - SHANOIR_KEYCLOAK_URL
      - SHANOIR_KEYCLOAK_INTERNAL_URL
      - SHANOIR_MIGRATION
      - SHANOIR_STORAGE_TYPE
      - S3_ENDPOINT
      - S3_REGION
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET_STUDIES
    volumes:
      - "logs:/var/log/shanoir-ng-logs"
      - certificate-share-data:/etc/ssl/certs/java:ro
      - "studies-data:/var/studies-data" # persistent
      - "bids-data:/var/bids-data" # temporary, participants.tsv
      - "tmp:/tmp"
    networks:
      - shanoir_ng_network
    ports:
     - "9902:9902"
     - "9912:9912"
    depends_on:
      init-cert-and-logs:
        condition: service_completed_successfully
      database-migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      users:
        condition: service_started
  #
  # Import microservice - native
  #
  import:
    container_name: "${SHANOIR_PREFIX}import"
    build: !reset null
    image: "shanoir-ng-import-native:latest"
    entrypoint: ["/workspace/org.shanoir.ng.ShanoirImportApplication",
                 "-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts",
                 "-Djavax.net.ssl.trustStorePassword=changeit",
                 "-Djavax.net.ssl.trustStoreType=JKS"]
    environment:
      - SHANOIR_PREFIX
      - SHANOIR_URL_SCHEME
      - SHANOIR_URL_HOST
      - SHANOIR_KEYCLOAK_URL
      - SHANOIR_KEYCLOAK_INTERNAL_URL
      - SHANOIR_MIGRATION
    volumes:
      - "logs:/var/log/shanoir-ng-logs"
      - certificate-share-data:/etc/ssl/certs/java:ro
      - "tmp:/tmp"
    networks:
      - shanoir_ng_network
    ports:
     - "9903:9903"
     - "9913:9913"
     # uncomment below for local testing of import-from-pacs, enable:
     # pacs-to-ms-import: c-move from dcm4chee arc light to ms import
     # do not add by default, as it blocks local ShUp from using 44105
     # - "44105:44105"
    depends_on:
      init-cert-and-logs:
        condition: service_completed_successfully
      database-migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      users:
        condition: service_started
