#!/bin/bash

set -e

. /bin/entrypoint_common


require SHANOIR_X_FORWARDED
x_forwarded_headers() {
	if [ "$SHANOIR_X_FORWARDED" = "generate" ] ; then
		echo 'proxy_set_header 	X-Forwarded-For $remote_addr;'
		echo 'proxy_set_header	X-Forwarded-Proto $scheme;'
	fi
}

(
	x_forwarded_headers

	cat /etc/nginx/shanoir.template.conf

	if [ -z "$SHANOIR_DEV" ] ; then
		cat /etc/nginx/shanoir.template.prod.conf
	else
		cat /etc/nginx/shanoir.template.dev.conf
	fi
) >/etc/nginx/shanoir.conf

(
	x_forwarded_headers

	cat /etc/nginx/ohif-viewer.template.conf

) >/etc/nginx/ohif-viewer.conf


require SHANOIR_URL_HOST
require SHANOIR_URL_SCHEME
require SHANOIR_VIEWER_OHIF_URL_HOST
require SHANOIR_VIEWER_OHIF_URL_SCHEME
optional SHANOIR_PREFIX

cp "/etc/nginx/$SHANOIR_URL_SCHEME.conf" /etc/nginx/server.conf

sed -i "s/SHANOIR_VIEWER_OHIF_URL_HOST/$SHANOIR_VIEWER_OHIF_URL_HOST/g
	s/SHANOIR_VIEWER_OHIF_URL_SCHEME/$SHANOIR_VIEWER_OHIF_URL_SCHEME/g
" /etc/nginx/server.conf /etc/nginx/shanoir.conf /etc/nginx/html/assets/env.js

sed -i "s/SHANOIR_URL_HOST/$SHANOIR_URL_HOST/g
" /etc/nginx/server.conf

sed -i "s/SHANOIR_PREFIX/$SHANOIR_PREFIX/g
" /etc/nginx/shanoir.conf /etc/nginx/ohif-viewer.conf


configure_instance()
{
	local user_color="${SHANOIR_INSTANCE_COLOR:-#813371}"

	local instance_color="transparent"
	if [ -n "$SHANOIR_INSTANCE_NAME" ] ; then
		instance_color="$user_color"
	fi

	sed -i "s\"SHANOIR_INSTANCE_NAME\"$SHANOIR_INSTANCE_NAME\"g
		s/SHANOIR_INSTANCE_COLOR/$instance_color/g
		s/SHANOIR_USER_COLOR/$user_color/g
		" /etc/nginx/html/assets/css/common.css /etc/nginx/html/styles*.css
}

configure_keycloak_adapter_mode()
{
	sed -i "s/'SHANOIR_KEYCLOAK_ADAPTER_MODE'/'$SHANOIR_KEYCLOAK_ADAPTER_MODE'/g
		" /etc/nginx/html/index.html
}

optional SHANOIR_INSTANCE_COLOR
optional SHANOIR_INSTANCE_NAME
configure_instance

optional SHANOIR_KEYCLOAK_ADAPTER_MODE
configure_keycloak_adapter_mode

abort_if_error

nginx -t
exec "$@"
