location = / {
    return 301 /shanoir-ng/welcome;
}

#
# static content
#
# static files for all requests for /*
location /shanoir-ng/ {
	alias   /etc/nginx/html/;
	try_files $uri$args $uri$args/ $uri $uri/ @default;

	# default lifetime
	expires +1h;

	# reduced lifetime for assets containing code w/o fingerprint
	location ~* ^/shanoir-ng/assets/.*\.(html|js|css|map)$ {
		expires +5m;
	}

	# longer lifetime for images and fonts
	location ~* ^/shanoir-ng/assets/.*\.(jpg|png|gif|svg|ttf|woff2)$ {
		expires +6h;
	}

	# very long lifetime for fingerprinted assets (*-XXXXXXXX.xxx)
	location ~ '^/shanoir-ng/(media/)?[^/]*-[0-9A-Z]{8}\\.[a-z0-9.]*$' {
		expires +1w;
	}
}

# default content (index.html)
# served with a reduced lifetime
location @default {
	try_files /index.html =404;
	expires +5m;
}
