#
# Keycloak
#
location /auth/ {
	# Forward requests to the keycloak server
	#
	# This whitelist covers only the locations needed by ordinary users
	# 	- /auth/js/
	# 	- /auth/resources/
	# 	- /auth/realms/shanoir-ng/
	location ~ ^/auth/(js|resources|realms/shanoir-ng)/
	{
		proxy_pass http://SHANOIR_KEYCLOAK_HOST:8080;
	}

	# Disallow all other locations (master realm, admin, ...)
	return 404;
}