
server:
  port: 9915
spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true
  autoconfigure.exclude: org.springframework.boot.amqp.autoconfigure.RabbitAutoConfiguration
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
# logging configuration
logging:
  file:
    name: /var/log/shanoir-ng-logs/shanoir-ng-preclinical.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework.amqp: OFF

#################
# DO NOT CHANGE #
#################
