#!/bin/bash

echo "Initialize MariaDB command"
/opt/mysql/init/mariadb_init.sh mysqld

echo "Create supervisor log directory"
mkdir -p /vol/log/supervisor

echo "Populate database"
mysql -u shanoir -pshanoir /opt/mysql/init/shanoirng_users.sql
