#!/bin/bash

echo "Initialize MariaDB command"
/opt/mysql/init/mariadb_init.sh mysqld

echo "Create supervisor log directory"
mkdir -p /vol/log/supervisor

service mysql start
echo "Populate database"
mysql -u shanoir -pshanoir shanoir_ng_users < /dk/shanoirng_users.sql
echo "Stop mysql process"
mysqladmin -u root -p$MYSQL_ROOT_PASSWORD shutdown

echo "Initialize Keycloak database"
java -jar shanoir-ng-keycloak-init.jar --spring.profiles.active=qualif
