#!/bin/bash

echo "Initialize MariaDB command"
/opt/mysql/init/mariadb_init.sh mysqld

echo "Create supervisor log directory"
mkdir -p /vol/log/supervisor

echo "Populate database"
service mysql start
mysql -u shanoir -pshanoir shanoir_ng_users < /dk/shanoirng_users.sql
service mysql stop	
