#!/bin/bash

set -e

. /bin/entrypoint_common

optional SHANOIR_PREFIX
require  SHANOIR_MIGRATION
require  SHANOIR_URL_HOST
require  SHANOIR_URL_SCHEME

require	 SHANOIR_ADMIN_EMAIL
require	 SHANOIR_SMTP_HOST

handle_microservice_migration

case "$SHANOIR_MIGRATION" in
dev|init)
	sync="--syncAllUsersToKeycloak=true" #FIXME: why can't we use an env var here?
	;;
*)
	sync="--syncAllUsersToKeycloak=false"
	;;
esac

# Rabbit MQ default environnement variable to set
export SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true

abort_if_error

run_microservice "$@" "$sync"
