#!/bin/bash

set -e

. /bin/entrypoint_common

require  SHANOIR_MIGRATION

handle_microservice_migration

case "$SHANOIR_MIGRATION" in
auto|init)
	sync="--syncAllUsersToKeycloak=true" #FIXME: why can't we use an env var here?
	;;
*)
	sync="--syncAllUsersToKeycloak=false"
	;;
esac


abort_if_error

run_microservice "$@" "$sync"
