#!/bin/bash

set -e

. /bin/entrypoint_common

optional SHANOIR_PREFIX
optional SHANOIR_DB_HOST
optional SHANOIR_DB_PORT
optional SHANOIR_DB_NAME
require  SHANOIR_MIGRATION
require  SHANOIR_URL_HOST
require  SHANOIR_URL_SCHEME

export  SHANOIR_NOTIFICATION_EMAIL
export	SHANOIR_NOTIFICATION_NAME
export  DEV_USERS_DEFAULT_PASSWORD
require	  SHANOIR_SMTP_HOST

optional  SHANOIR_CERTIFICATE
require   SHANOIR_CERTIFICATE_PEM_CRT
require   SHANOIR_CERTIFICATE_PEM_KEY

handle_microservice_migration

case "$SHANOIR_MIGRATION" in
dev|init)
	sync="--syncAllUsersToKeycloak=true" #FIXME: why can't we use an env var here?
	# mitigate a race condition (the syncAllUsersToKeycloak task may
	# terminate just after the server startup)
	init_wait 10
	;;
*)
	sync="--syncAllUsersToKeycloak=false"
	;;
esac

# Rabbit MQ default environment variable to set
export SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true

abort_if_error

run_microservice "$@" "$sync"
