#!/bin/sh

# runtime config
configure-hosts
override -e SHANOIR_SERVER_URL -e SHANOIR_INSTANCE /etc/nginx/nginx.conf /etc/nginx/html/index.html /etc/nginx/html/app.*.js

mkdir -p /vol/log

exec nginx -g 'daemon off;'
