#!/bin/bash

set -e

. /bin/entrypoint_common

require SHANOIR_URL_SCHEME
require SHANOIR_URL_HOST
require VIEWER_URL_SCHEME
require VIEWER_URL_HOST

sed -i "s/SHANOIR_URL_SCHEME/$SHANOIR_URL_SCHEME/g" /usr/share/nginx/html/app-config.js

sed -i "s/SHANOIR_URL_HOST/$SHANOIR_URL_HOST/g" /usr/share/nginx/html/app-config.js

sed -i "s/VIEWER_URL_SCHEME/$VIEWER_URL_SCHEME/g" /usr/share/nginx/html/app-config.js

sed -i "s/VIEWER_URL_HOST/$VIEWER_URL_HOST/g" /usr/share/nginx/html/app-config.js


