apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: certificate-share-data
  name: certificate-share-data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
