apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: extra-data
  name: extra-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
