apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-database
  name: keycloak-database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak-database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: keycloak
        image: keycloak-database
        name: keycloak-database
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: keycloak-database-data
      restartPolicy: Always
      volumes:
      - name: keycloak-database-data
        persistentVolumeClaim:
          claimName: keycloak-database-data
status: {}
