apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ldap
  name: ldap
spec:
  ports:
    - name: "389"
      port: 389
      targetPort: 389
  selector:
    io.kompose.service: ldap
