apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ldap
  name: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ldap
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ldap
    spec:
      containers:
        - env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: HTTP_PORT
                  name: variables-env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: variables-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: variables-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: variables-env
            - name: STORAGE_DIR
              valueFrom:
                configMapKeyRef:
                  key: STORAGE_DIR
                  name: variables-env
          image: dcm4che/slapd-dcm4chee:2.6.2-27.0
          name: ldap
          ports:
            - containerPort: 389
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/openldap/openldap-data
              name: dcm4chee-ldap-data
            - mountPath: /etc/openldap/slapd.d
              name: dcm4chee-sldap-data
      restartPolicy: Always
      volumes:
        - name: dcm4chee-ldap-data
          persistentVolumeClaim:
            claimName: dcm4chee-ldap-data
        - name: dcm4chee-sldap-data
          persistentVolumeClaim:
            claimName: dcm4chee-sldap-data
