apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: ghcr.io/fli-iam/shanoir-ng/nginx:NG_v2.5.1
          name: shanoir-ng-nginx
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/nginx
              name: logs
            - mountPath: /opt/ssl
              name: certificate-share-data
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: certificate-share-data
          persistentVolumeClaim:
            claimName: certificate-share-data
            readOnly: true
