apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: solr-data
  name: solr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
