apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: solr
    spec:
      containers:
        - env:
            - name: SOLR_LOG_LEVEL
              value: SEVERE
          image: ghcr.io/fli-iam/shanoir-ng/solr:NG_v2.5.1
          name: solr
          ports:
            - containerPort: 8983
              protocol: TCP
          volumeMounts:
            - mountPath: /var/solr
              name: solr-data
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
