#!/usr/bin/python3

import os
import subprocess

from dk.migration import migration, die, run

def apply_mysql(filename):
    print("apply %r" % filename)
    subprocess.check_call("mysql -h mysql -u shanoir -pshanoir shanoirdb <%r" %
            os.path.join("/opt/cfg/", filename), shell = True)


@migration("", "2.0.1")
def _():
    apply_mysql("studies_tables_v2.0.1.sql")
    os.system("/opt/cfg/studies_migration_v2.0.1.py 1")

run()
