#!/usr/bin/python3

import os
import subprocess

from dk.migration import migration, die, run

subprocess.check_call(["configure-hosts"])

def apply_mysql(filename):
    print("apply %r" % filename)
    subprocess.check_call("mysql -h localhost -u shanoir -pshanoir shanoir_ng_studies <%r" %
            os.path.join("/opt/cfg/", filename), shell = True)


@migration("", "2.0.1")
def _():
    apply_mysql("studies_tables_v2.0.1.sql")
    subprocess.check_call(["/opt/cfg/studies_migration_v2.0.1.py", "1"])

print("Start the mysql server")
run-mysql </dev/null &
pid=$!
wait-mysql --timeout=5

run()

print("Stop mysql process")
kill $pid
wait
