#!/bin/bash

export KEYCLOAK_USER="admin"
export KEYCLOAK_PASSWORD="admin"

set -e

cd /opt/keycloak/bin

echo "Initialise the mysql database"
init-mysql </dev/null

echo "Create the '$KEYCLOAK_USER' user with password '$KEYCLOAK_PASSWORD'"
./add-user-keycloak.sh --user "$KEYCLOAK_USER" --password "$KEYCLOAK_PASSWORD"

echo "Start mysqld"
run-mysql&
my_pid=$!

echo "Initialise the keycloak db"
run-msapp --init

sleep 1	 # race condition (with /vol/rw/lock)

echo "Run keycloak"
run-msapp&
kc_pid=$!
# wait until the jboss server is ready
wait-keycloak

echo "Get an authentication token from the server"
./kcadm.sh config credentials --server http://localhost:8080/auth \
	--realm master --user "$KEYCLOAK_USER" --password "$KEYCLOAK_PASSWORD"


echo "Create user 'ng-users' in the master realm"
# generate a password
ngusers_password="`head -c 24 /dev/urandom | base64`"
# create user
./kcadm.sh create users -r master -s username=ng-users -s enabled=true
# grant permission to manage the users of shanoir-ng-realm
./kcadm.sh add-roles -r master --uusername ng-users --cclientid shanoir-ng-realm	\
	--rolename view-realm --rolename view-users --rolename manage-users
# set the password
./kcadm.sh set-password -r master --username ng-users <<EOF
$ngusers_password
EOF

echo "Stop keycloak"
kill $kc_pid
wait $kc_pid || true

echo "Stop mysqld"
kill $my_pid

wait

cat <<EOF

Keycloak initialisation completed

#####################################################################
##                                                                 ##
##  WARNING: the admin password is set to 'admin'                  ##
##           you should change it as soon as possible!             ##
##                                                                 ##
##                                                                 ##
##  credential for shanoir-ng-users:                               ##
##    - username:  ng-users                                        ##
##    - password:  $ngusers_password                ##
##                                                                 ##
##  now you should initialise shanoir-ng-users with this password  ##
##    -> /dk/container_init $ngusers_password       ##
##                                                                 ##
#####################################################################

EOF

