#!/bin/bash

export KEYCLOAK_USER="admin"
export KEYCLOAK_PASSWORD="admin"

set -e

cd /opt/keycloak/bin

echo "Initialise the mysql database"
init-mysql </dev/null

echo "Create the '$KEYCLOAK_USER' user with password '$KEYCLOAK_PASSWORD'"
./add-user-keycloak.sh --user "$KEYCLOAK_USER" --password "$KEYCLOAK_PASSWORD"


echo "Start server"
run-supervisor&
pid=$!

# wait until the jboss server is ready
wait-keycloak

echo "Get an authentication token from the server"
./kcadm.sh config credentials --server http://localhost:8080/auth \
	--realm master --user "$KEYCLOAK_USER" --password "$KEYCLOAK_PASSWORD"

echo "Create realm 'shanoir-ng'"
./kcadm.sh create realms -s realm=shanoir-ng -s enabled=true


for client in /opt/cfg/clients/*
do
	echo "Create client '`basename "$client" .json`'"
	./kcadm.sh create clients -r shanoir-ng -f "$client"
done

echo "Initialize Keycloak configuration"
java -jar /opt/cfg/shanoir-ng-keycloak-init.jar

echo "Kill the server"
kill "$pid"
wait "$pid"

cat <<EOF

Keycloak initialisation completed

#####################################################################
##                                                                 ##
##  WARNING: the admin password is set to 'admin'                  ##
##                                                                 ##
##           you should change it immediately                      ##
##                                                                 ##
#####################################################################

EOF

