/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DescriptorEnvironmentvariables { 
    /**
     * The environment variable name (identifier) containing only alphanumeric characters and underscores. Example: \"PROGRAM_PATH\".
     */
    name: string;
    /**
     * The value of the environment variable.
     */
    value: string;
    /**
     * Description of the environment variable.
     */
    description?: string;
}