/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DescriptorSuggestedresources { 
    /**
     * The requested number of cpu cores to run the described application
     */
    cpuCores?: number;
    /**
     * The requested number of GB RAM to run the described application
     */
    ram?: number;
    /**
     * The requested number of GB of storage to run the described application
     */
    diskSpace?: number;
    /**
     * The requested number of nodes to spread the described application across
     */
    nodes?: number;
    /**
     * Estimated wall time of a task in seconds.
     */
    walltimeEstimate?: number;
}