/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DescriptorGroups { 
    /**
     * A short, unique, informative identifier containing only alphanumeric characters and underscores. Typically used to generate variable names. Example: \"outfile_group\".
     */
    id: string;
    /**
     * A human-readable name for the input group.
     */
    name: string;
    /**
     * Description of the input group.
     */
    description?: string;
    /**
     * IDs of the inputs belonging to this group.
     */
    members: Array<string>;
    /**
     * True if only one input in the group may be active at runtime.
     */
    mutuallyExclusive?: boolean;
    /**
     * True if at least one of the inputs in the group must be active at runtime.
     */
    oneIsRequired?: boolean;
    /**
     * True if members of the group need to be toggled together
     */
    allOrNone?: boolean;
}