/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DescriptorOutputfiles { 
    /**
     * A short, unique, informative identifier containing only alphanumeric characters and underscores. Typically used to generate variable names. Example: \"data_file\"
     */
    id: string;
    /**
     * A human-readable output name. Example: 'Data file'
     */
    name: string;
    /**
     * Output description.
     */
    description?: string;
    /**
     * A string contained in command-line, substituted by the output value and/or flag at runtime.
     */
    valueKey?: string;
    /**
     * Describes the output file path relatively to the execution directory. May contain input value keys. Example: \"results/[INPUT1]_brain.mnc\".
     */
    pathTemplate: string;
    /**
     * List of file extensions that will be stripped from the input values before being substituted in the path template. Example: [\".nii\",\".nii.gz\"].
     */
    pathTemplateStrippedExtensions?: Array<string>;
    /**
     * True if output is a list of value.
     */
    list?: boolean;
    /**
     * True if output may not be produced by the tool.
     */
    optional?: boolean;
    /**
     * Option flag of the output, involved in the value-key substitution. Examples: -o, --output
     */
    commandLineFlag?: string;
    /**
     * Separator used between flags and their arguments. Defaults to a single space.
     */
    commandLineFlagSeparator?: string;
    /**
     * Specifies that this output filepath will be given as an absolute path.
     */
    usesAbsolutePath?: boolean;
    /**
     * An array of strings that may contain value keys. Each item will be a line in the configuration file.
     */
    fileTemplate?: Array<string>;
}