/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DescriptorAssertions } from './descriptorAssertions';

export interface DescriptorTests { 
    /**
     * Name of the test-case
     */
    name: string;
    invocation: any;
    assertions: DescriptorAssertions;
}