/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DescriptorAssertionsOutputfiles { 
    /**
     * Id refering to an output-file
     */
    id: string;
    /**
     * MD5 checksum string to match against the MD5 checksum of the output-file specified by the id object
     */
    md5Reference?: string;
}