/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ErrorCodeAndMessage { 
    errorCode: number;
    errorMessage: string;
    /**
     * optional pieces of information about the error(s)
     */
    errorDetails?: { [key: string]: any; };
}