/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 export type ParameterType = 'File' | 'String' | 'Boolean' | 'Int64' | 'Double' | 'List';

 export const ParameterType = {
     File: 'File' as ParameterType,
     String: 'String' as ParameterType,
     Boolean: 'Boolean' as ParameterType,
     Int64: 'Int64' as ParameterType,
     Double: 'Double' as ParameterType,
     List: 'List' as ParameterType
 };