/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Path { 
    /**
     * A valid path, slash-separated. It must be consistent with the path of files and directories uploaded and downloaded by clients. For instance, if a user uploads a directory structure \"dir/{file1.txt,file2.txt}\", it is expected that the path of the first file will be \"[prefix]/dir/file1.txt\" and that the path of the second file will be \"[prefix]/dir/file2.txt\" where [prefix] depends on the upload parameters, in particular destination directory.
     */
    platformPath: string;
    /**
     * Date of last modification, in seconds since the Epoch (UNIX timestamp).
     */
    lastModificationDate: number;
    /**
     * True if the path represents a directory.
     */
    isDirectory: boolean;
    /**
     * For a file, size in bytes. For a directory, sum of all the sizes of the files contained in the directory (recursively).
     */
    size?: number;
    /**
     * Id of the Execution that produced the Path.
     */
    executionId?: string;
    /**
     * mime type based on RFC 6838.
     */
    mimeType?: string;
}