/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorCodeAndMessage } from './errorCodeAndMessage';
import { PipelineParameter } from './pipelineParameter';

export interface Pipeline { 
    identifier: string;
    name: string;
    version: string;
    description?: string;
    /**
     * true if the user who requested the pipeline can execute it
     */
    canExecute?: boolean;
    parameters?: Array<PipelineParameter>;
    /**
     * the properties (as keys) and their values that describe the pipeline. The properties used must be listed in the \"supportedPipelineProperties\" of the \"getPlatformProperties\" method.
     */
    properties: { [key: string]: string; };
    errorCodesAndMessages?: Array<ErrorCodeAndMessage>;
}