/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelObject } from './modelObject';
import { ParameterType } from './parameterType';

export interface PipelineParameter { 
    name: string;
    type: ParameterType;
    isOptional: boolean;
    isReturnedValue: boolean;
    /**
     * Default value. It must be consistent with the parameter type.
     */
    defaultValue?: ModelObject;
    description?: string;
}