/**
 * CARMIN - Common API for Research Medical Imaging Network
 * REST API for exchanging data and remotely calling pipelines.
 *
 * OpenAPI spec version: 0.3.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * 
 * 
 * @Alaeessaki, this class is not generated well in TS, so i recovert a java client class to this ts.
 */

export enum SupportedModulesEnum {
  PROCESSING,
  DATA,
  ADVANCEDDATA,
  MANAGEMENT,
  COMMERCIAL
}

export interface PlatformProperties {

  supportedModules: Array<SupportedModulesEnum>;
  defaultLimitListExecutions: number;
  email: string;
  platformDescription: string;
  minAuthorizedExecutionTimeout: number;
  maxAuthorizedExecutionTimeout: number;
  defaultExecutionTimeout: number;
  unsupportedMethods: Array<string>;
  studiesSupport: boolean;
  defaultStudy: string;
  supportedAPIVersion: string;
  ssupportedPipelineProperties: Array<string>;


}