#!/bin/bash

set -e

. /bin/entrypoint_common

require  SHANOIR_ADMIN_EMAIL
require  SHANOIR_ADMIN_NAME
optional SHANOIR_PREFIX
require  SHANOIR_SMTP_HOST
require  SHANOIR_URL_SCHEME
require  SHANOIR_URL_HOST
require  SHANOIR_VIEWER_OHIF_URL_SCHEME
require  SHANOIR_VIEWER_OHIF_URL_HOST

mkdir -p /tmp/import
sed "	s/SHANOIR_ADMIN_NAME/$SHANOIR_ADMIN_NAME/g
		s/SHANOIR_ADMIN_EMAIL/$SHANOIR_ADMIN_EMAIL/g
		s/SHANOIR_SMTP_HOST/$SHANOIR_SMTP_HOST/g
		s/SHANOIR_URL_SCHEME/$SHANOIR_URL_SCHEME/g
		s/SHANOIR_URL_HOST/$SHANOIR_URL_HOST/g
		s/SHANOIR_VIEWER_OHIF_URL_SCHEME/$SHANOIR_VIEWER_OHIF_URL_SCHEME/g
		s/SHANOIR_VIEWER_OHIF_URL_HOST/$SHANOIR_VIEWER_OHIF_URL_HOST/g
		s/VIP_CLIENT_SECRET/$VIP_CLIENT_SECRET/g
"		/opt/keycloak/shanoir-ng-realm.json > /tmp/import/shanoir-ng-realm.json

sed -i -E "s/SHANOIR_URL_SCHEME/$SHANOIR_URL_SCHEME/g" /opt/keycloak/themes/shanoir-theme/login/template.ftl 
sed -i -E "s/SHANOIR_URL_HOST/$SHANOIR_URL_HOST/g" /opt/keycloak/themes/shanoir-theme/login/template.ftl 

#
# keycloak options
# see: https://www.keycloak.org/server/all-config
#
# NOTE: options that must also be set at build-time (eg: KC_DB,
#       KC_HTTP_RELATIVE_PATH) are set in the Dockerfile.
#
export KC_PROXY_HEADERS="${KC_PROXY_HEADERS:-xforwarded}"
export KC_HTTP_ENABLED="${KC_HTTP_ENABLED:-true}"
export KC_SPI_THEME_WELCOME_THEME="shanoir-theme"

# we disable strict hostname checking by default because:
# - the reverse proxy in production implements this check
# - since the 'nginx' container does not expose the master realm to the
#   outside, disabling strict checking allows us to reach the admin console
#   at http://localhost:8080/auth/admin/
export KC_HOSTNAME_STRICT=false
export KC_HOSTNAME_STRICT_BACKCHANNEL=false


export KC_DB_URL=jdbc:mysql://"${DB_ADDR:-${SHANOIR_PREFIX}keycloak-database}":"${DB_PORT:-3306}"/"${DB_DATABASE:-keycloak}"
export KC_DB_USERNAME="${DB_USER:-keycloak}"
export KC_DB_PASSWORD="${DB_PASSWORD:-password}"

# creation of the admin account
export KEYCLOAK_ADMIN="$SHANOIR_KEYCLOAK_USER"
export KEYCLOAK_ADMIN_PASSWORD="$SHANOIR_KEYCLOAK_PASSWORD"

require  SHANOIR_MIGRATION
STARTED_PATTERN=' \[io.quarkus\] \(main\) Keycloak .* started in [0-9.]+*s'
extra=("-Dms.users.url=http://${SHANOIR_PREFIX}users:9901"
       "-Dallowed.admin.ips=${SHANOIR_ALLOWED_ADMIN_IPS}")

case "$SHANOIR_MIGRATION" in
auto|dev)
	# create the shanoir-ng realm if it does not exist yet
	# NOTE: this will never reimport the realm when its config is changed
	#       (the realm has to be reimported manually)
	mkdir -p /opt/keycloak/data/import
	cp /tmp/import/shanoir-ng-realm.json /opt/keycloak/data/import/
	extra+=(start --import-realm)
	;;
init)
	# wipe out the shanoir-ng realm and recreate it
	extra+=(import --file /tmp/import/shanoir-ng-realm.json --override true)
	;;
never)
	# FIXME: should we provide a facade for these too
	# TODO: ensure that the realm config is up-to-date
	#-> add an optional data volume to store the config of the imported realm
	extra+=(start)
	;;

import)
	# Import the shanoir-ng users
	#
	# The exported users shall be provided in /import/shanoir-ng-users-*.json
	#
	# The realm file /import/shanoir-ng-realm.json is ignored (we use the
	# /tmp/import/shanoir-ng-realm.json generated above)
	#
	# Fails if the users file is not present.

	IMPORT_DIR="/import"
	if [ ! -d "$IMPORT_DIR" ] ; then
		error "import dir '$IMPORT_DIR' is not present"
	elif ! (shopt -s failglob ; ln -s "$IMPORT_DIR"/shanoir-ng-users-*.json /tmp/import/)
	then
		error "import dir '$IMPORT_DIR' does not contain any users file"
	else
		extra+=(import --dir /tmp/import --override true)
	fi
	;;

export)
	# Export the shanoir-ng realm
	#
	# The realm is exported as:
	#	/export/shanoir-ng-realm.json
	#	/export/shanoir-ng-users-0.json
	#
	# Fails if the /export dir is not present or not empty

	EXPORT_DIR="/export"
	if [ ! -d "$EXPORT_DIR" ] ; then
		error "export dir '$EXPORT_DIR' is not present"
	elif [ -n "`ls -A "$EXPORT_DIR"`" ] ; then
		error "export dir '$EXPORT_DIR' is not empty"
	else
		extra+=(export --realm shanoir-ng --dir "$EXPORT_DIR" --users same_file)
	fi
	;;
esac
unset SHANOIR_KEYCLOAK_USER SHANOIR_KEYCLOAK_PASSWORD


abort_if_error

echo "Rebuild Keycloak to pick up any new providers/themes…"
/opt/keycloak/bin/kc.sh build

# run keycloak
exec env "$@" "${extra[@]}"
