#!/bin/sh

die() {
	echo "error: $*" >&2
	exit 1
}

[ -n "$PROFILE" ] || die "env var PROFILE is empty (should contain either prod, qualif or dev)"


# abort on error
set -e

configure-hosts


echo "Initialize MariaDB and populate it"
init-mysql < /dev/null

echo "Create supervisor log directory"
mkdir -p /vol/log/supervisor

echo "Create shanoir ms log directory"
mkdir -p /vol/log/ms
chown shanoir: /vol/log/ms

echo "Start the mysql server"
run-mysql </dev/null &
pid=$!
wait-mysql --timeout=5

echo "Stop mysql process"
kill $pid
wait
