# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

######################################
# Default profile is production      #
######################################
server:
  port: 9903
  error:
    whitelabel:
      enabled: false
##### Database #####
spring:
  jackson:
    mapper:
      use-getters-as-setters: false
  rabbitmq:
    host: ${SHANOIR_PREFIX}rabbitmq
    port: 5672
    username: guest
    password: guest
  session:
    store-type: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB

# logging configuration
logging:
  file:
    name: /var/log/shanoir-ng-logs/shanoir-ng-nifti-conversion.log
  level:
    org.springframework.web: ERROR
    org.shanoir: INFO
shanoir:
  database: disable
  conversion:
    converters:
      mriconverter: "/opt/nifti-converters/mriconverter/MRIFileManager/MRIManager.jar"
  import:
    series:
      # this long name has been kept, as Elise and Isabelle know it like this; to find it for further adaptions in later time
      # Also during the nifti conversion, it will be reconstructed as 4D volumes.
      seriesProperties: seriesDescription==*ASL*;seriesDescription==*asl*;protocolName==*ASL*;seriesDescription==*VIBE*DYN*;seriesDescription==*MoCoSeries*;seriesDescription==*DIFF*;seriesDescription==*Diff*;seriesDescription==*diff*;seriesDescription==*DTI*;seriesDescription==*DWI*;seriesDescription==*PERF*;seriesDescription==*Perf*;seriesDescription==*perf*;seriesDescription==*BOLD*;seriesDescription==*Bold*;seriesDescription==*bold*;seriesDescription==*intermediate t-Map*;protocolName==*DYN*;protocolName==*Dyn*;protocolName==*dyn*;seriesDescription==*QSM*;seriesDescription==*qsm*;seriesDescription==*RELAXO*;seriesDescription==*relaxo*;seriesDescription==*Relaxo*;seriesDescription==IRMF;protocolName==IRMF;seriesDescription==*mc*gse*;protocolName==*mc*gse*;seriesDescription==*MULTIGRE*;protocolName==*MULTIGRE*;seriesDescription==*multigre*;protocolName==*multigre*;seriesDescription==*Multigre*;protocolName==*Multigre*;
--- 
spring:
  config.activate.on-profile: dev
  jackson:
    mapper:
      use-getters-as-setters: false
  rabbitmq:
    host: ${SHANOIR_PREFIX}rabbitmq
    port: 5672
    username: guest
    password: guest
  session:
    store-type: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB

# logging configuration
logging:
  pattern:
    file: '%d{yyyy-MM-dd_HH:mm:ss.SSS} %-5level [%mdc{username}] %logger{35} - %msg%n'
  file:
    name: /var/log/shanoir-ng-logs/shanoir-ng-nifti-conversion.log
  level:
    org.springframework.web: ERROR
    org.shanoir: INFO
# Shanoir configurations
shanoir:
  database: disable
  conversion:
    converters:
      path: /opt/nifti-converters/
        # Format "tag==value;". If in the serie, the dicom value equals the "value" for the "tag", then use clidcm instead of dcmnii to convert from dicom to nifti
      mriconverter: "/opt/nifti-converters/mriconverter/MRIFileManager/MRIManager.jar"
