name: Checkstyle Java Code

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Download dependencies
        run: mvn dependency:go-offline --batch-mode
        working-directory: ./shanoir-ng-back/

      - name: Run Checkstyle
        run: |
          set +e
          EXIT=0
          ROOT_DIR=$(pwd)
          # Liste tous les dossiers commençant par `shanoir-ng-`
          for module_path in shanoir-ng-*/; do
            # Retire le slash final pour obtenir l'artifactId
            module=${module_path%/}
            echo "=== Checkstyle sur $module ==="
            mvn -B -pl "$module" checkstyle:check \
                -Dcheckstyle.config.location="$ROOT_DIR/checkstyle.xml"
            if [[ $? -ne 0 ]]; then
              EXIT=1
            fi
          done
          exit $EXIT
        working-directory: ./shanoir-ng-back/