name: Checkstyle Java Code

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Download dependencies
        run: mvn dependency:go-offline --batch-mode
        working-directory: ./shanoir-ng-back/

      - name: Run Checkstyle
        run: mvn checkstyle:check --batch-mode -Dcheckstyle.config.location=${PWD}/checkstyle.xml
        working-directory: ./shanoir-ng-back/