name: Checkstyle Java Code

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Download dependencies
        run: mvn dependency:go-offline --batch-mode
        working-directory: ./shanoir-ng-back/

      - name: Run Checkstyle
        run: |
          set +e
          EXIT=0
          ROOT_DIR=$(pwd)
          
          modules=(
            "org.shanoir-ng:shanoir-ng-ms-common"
            "org.shanoir-ng:shanoir-ng-study-rights"
            "org.shanoir-ng:shanoir-ng-users"
            "org.shanoir-ng:shanoir-ng-anonymization"
            "org.shanoir-ng:shanoir-ng-studies"
            "org.shanoir-ng:shanoir-ng-datasets"
            "org.shanoir-ng:shanoir-ng-exchange"
            "org.shanoir-ng:shanoir-ng-import"
            "org.shanoir-ng:shanoir-ng-preclinical"
            "org.shanoir-ng:shanoir-ng-nifti-conversion"
          )

          for coord in "${modules[@]}"; do
            echo "=== Checkstyle sur $coord ==="
            mvn -B -pl "$coord" checkstyle:check \
                -Dcheckstyle.config.location="$ROOT_DIR/checkstyle.xml"
            [[ $? -ne 0 ]] && EXIT=1
          done

          exit $EXIT
        working-directory: ./shanoir-ng-back/