# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

name: Check code style

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Download dependencies
        run: mvn dependency:go-offline --batch-mode
        working-directory: ./shanoir-ng-back/

      - name: Run Checkstyle
        run: |
          set +e
          EXIT=0
          ROOT_DIR=$(pwd)
          
          modules=(
            "org.shanoir-ng:shanoir-ng-ms-common"
            "org.shanoir-ng:shanoir-ng-study-rights"
            "org.shanoir-ng:shanoir-ng-users"
            "org.shanoir.anonymization:anonymization"
            "org.shanoir-ng:shanoir-ng-studies"
            "org.shanoir-ng:shanoir-ng-datasets"
            "org.shanoir-ng:shanoir-ng-exchange"
            "org.shanoir-ng:shanoir-ng-import"
            "org.shanoir-ng:shanoir-ng-preclinical"
            "org.shanoir-ng:nifti-conversion"
          )

          for coord in "${modules[@]}"; do
            echo "=== Checkstyle sur $coord ==="
            mvn -B -pl "$coord" checkstyle:check \
                -Dcheckstyle.config.location="$ROOT_DIR/checkstyle.xml"
            [[ $? -ne 0 ]] && EXIT=1
          done

          exit $EXIT
        working-directory: ./shanoir-ng-back/

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./shanoir-ng-front/package-lock.json
      - name: Install dependencies
        working-directory: ./shanoir-ng-front/
        run: npm ci
      - name: Run ESLint
        working-directory: ./shanoir-ng-front/
        run: npm run lint