name: Checkstyle Java Code

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download dependencies
        run: mvn dependency:go-offline --batch-mode

      - name: Run Checkstyle
        run: mvn checkstyle:check --batch-mode