name: Release ShanoirUploader App

on:
  push:
    branches:
      - Laurent_SHUP_jpackage
    # paths: 
    #   - 'shanoir-uploader/**'
 

jobs:
  setup-version:
    runs-on: ubuntu-latest
    outputs:
      version_part: ${{ steps.get_tag.outputs.version_part }}
      release_tag: ${{ steps.get_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Get latest NG tag and generate SHUP release tag
        id: get_tag
        run: |
          latest_tag=$(git tag --list "SHUP_v*" --sort=-creatordate | head -n 1)
          echo "Latest_tag: $latest_tag"
          if [[ "$latest_tag" =~ SHUP_v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            version_part="${BASH_REMATCH[1]}"
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
            patch=$((patch + 1))
            new_tag="SHUP_v${major}.${minor}.${patch}"
            echo "version_part="${major}.${minor}.${patch}" >> "$GITHUB_OUTPUT"
            echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"
          else
            echo "No NG tag found"
            exit 1
          fi

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: cd shanoir-ng-parent && mvn clean package -DskipTests

      - name: Create custom runtime with jlink
        run: |
          jlink \
            --module-path $JAVA_HOME/jmods \
            --add-modules java.base,java.desktop \
            --output shanoir-uploader/target/custom-runtime \
            --compress 2 \
            --strip-debug \
            --no-header-files \
            --no-man-pages

      - name: Package .deb
        run: |
          cd shanoir-uploader
          mkdir target/packages
          mkdir -p target/lib
          cp target/shanoir-uploader-2.6.5.jar target/lib/
          jpackage \
            --type deb \
            --input target/lib \
            --dest target/packages \
            --name ShanoirUploader \
            --app-version ${{ needs.setup-version.outputs.version_part }} \
            --main-jar shanoir-uploader-2.6.5.jar \
            --main-class org.shanoir.uploader.ShanoirUploader \
            --runtime-image target/custom-runtime \
            --java-options "-Xmx2g" 

      - uses: actions/upload-artifact@v4
        with:
          name: shup-deb
          path: shanoir-uploader/target/packages/*.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: cd shanoir-ng-parent && mvn clean package -DskipTests

      - name: Create custom runtime with jlink
        run: |
          jlink `
            --module-path $Env:JAVA_HOME\jmods `
            --add-modules java.base,java.desktop `
            --output shanoir-uploader/target/custom-runtime `
            --compress 2 `
            --strip-debug `
            --no-header-files `
            --no-man-pages

      - name: Package .exe
        run: |
          cd shanoir-uploader
          mkdir target/packages
          mkdir -p target/lib
          cp target/shanoir-uploader-2.6.5.jar target/lib/
          jpackage `
            --vendor "Inria" `
            --copyright "© 2025 Inria" `
            --name ShanoirUploader `
            --app-version ${{ needs.setup-version.outputs.version_part }} `
            --type exe `
            --input target/lib `
            --dest target/packages `
            --main-jar shanoir-uploader-2.6.5.jar `
            --main-class org.shanoir.uploader.ShanoirUploader `
            --runtime-image target/custom-runtime `
            --java-options "-Xmx2g" `
            --icon src/main/resources/images/icon.ico `
            --win-menu `
            --win-shortcut `
            --win-dir-chooser `
            --win-per-user-install

      - uses: actions/upload-artifact@v4
        with:
          name: shup-exe
          path: shanoir-uploader/target/packages/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: cd shanoir-ng-parent && mvn clean package -DskipTests

      - name: Create custom runtime with jlink
        run: |
          jlink \
            --module-path $JAVA_HOME/jmods \
            --add-modules java.base,java.desktop \
            --output shanoir-uploader/target/custom-runtime \
            --compress 2 \
            --strip-debug \
            --no-header-files \
            --no-man-pages

      - name: Package .dmg
        run: |
          cd shanoir-uploader
          mkdir target/packages
          mkdir -p target/lib
          cp target/shanoir-uploader-2.6.5.jar target/lib/
          jpackage \
            --type dmg \
            --input target/lib \
            --dest target/packages \
            --name ShanoirUploader \
            --app-version ${{ needs.setup-version.outputs.version_part }} \
            --main-jar shanoir-uploader-2.6.5.jar \
            --main-class org.shanoir.uploader.ShanoirUploader \
            --runtime-image target/custom-runtime \
            --java-options "-Xmx2g"

      - uses: actions/upload-artifact@v4
        with:
          name: shup-dmg
          path: shanoir-uploader/target/packages/*.dmg

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.setup-version.outputs.release_tag }}
          name: ${{ needs.setup-version.outputs.release_tag }}
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
