name: Release ShanoirUploader App

on:
  push:
    branches:
      - Laurent_SHUP_jpackage
    # tags:
    #   - SHUP_v*
    # paths: 
    #   - 'shanoir-uploader/**'
 

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: cd shanoir-ng-parent && mvn clean package -DskipTests

      - name: Create custom runtime with jlink
        run: |
          jlink \
            --module-path $JAVA_HOME/jmods \
            --add-modules java.base,java.desktop \
            --output target/custom-runtime \
            --compress 2 \
            --strip-debug \
            --no-header-files \
            --no-man-pages

      - name: Package .deb
        run: |
          cd shanoir-uploader
          mkdir dist
          jpackage \
            --type deb \
            --input target \
            --dest dist \
            --name ShanoirUploader \
            --main-jar shanoir-uploader-9.0.0-jar-with-dependencies.jar \
            --main-class org.shanoir.uploader.ShanoirUploader \
            --runtime-image custom-runtime

      - uses: actions/upload-artifact@v4
        with:
          name: shup-deb
          path: shanoir-uploader/dist/*.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: cd shanoir-ng-parent && mvn clean package -DskipTests

      - name: Create custom runtime with jlink
        run: |
          jlink \
            --module-path $Env:JAVA_HOME\jmods \
            --add-modules java.base,java.desktop \
            --output target/custom-runtime \
            --compress 2 \
            --strip-debug \
            --no-header-files \
            --no-man-pages

      - name: Package .exe
        run: |
          cd shanoir-uploader
          mkdir dist
          jpackage `
            --app-version 1.0.1 `
            --vendor "Inria" `
            --copyright "© 2025 Inria" `
            --type exe `
            --input target `
            --dest dist `
            --name ShanoirUploader `
            --main-jar shanoir-uploader-9.0.0-jar-with-dependencies.jar `
            --main-class org.shanoir.uploader.ShanoirUploader `
            --runtime-image custom-runtime `
            --win-menu `
            --win-shortcut 

      - uses: actions/upload-artifact@v4
        with:
          name: shup-exe
          path: shanoir-uploader/dist/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: cd shanoir-ng-parent && mvn clean package -DskipTests

      - name: Create custom runtime with jlink
        run: |
          jlink \
            --module-path $JAVA_HOME/jmods \
            --add-modules java.base,java.desktop \
            --output target/custom-runtime \
            --compress 2 \
            --strip-debug \
            --no-header-files \
            --no-man-pages

      - name: Package .dmg
        run: |
          cd shanoir-uploader
          mkdir dist
          jpackage \
            --type dmg \
            --input target \
            --dest dist \
            --name ShanoirUploader \
            --main-jar shanoir-uploader-9.0.0-jar-with-dependencies.jar \
            --main-class org.shanoir.uploader.ShanoirUploader \
            --runtime-image custom-runtime

      - uses: actions/upload-artifact@v4
        with:
          name: shup-dmg
          path: shanoir-uploader/dist/*.dmg

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: SHUP_v1.0.1 # TODO : remplacer github.ref_name par le nom de la version
          name: SHUP_v1.0.1
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
