#!/bin/sh

cd /etc/shanoir-core-template || exit 1

# Compare old and new solr scheme.xml
for file in $(find . -maxdepth 1 -type f -name "schema.xml"); do
  if ! cmp -s -- "$file" "/var/solr/data/shanoir/$file"; then
    echo 'Deleting /var/solr/data (not up-to-date with the template), the index has to be rebuilt'
    rm -rf /var/solr/data
    break
  fi
done

echo "Solr index is up-to-date, no rebuild needed"

exec "$@"